pdf_extraction_task:
  description: >
    Read all PDF documents in the knowledge folder and extract the complete content from each.
    Ensure that any special characters, formatting, and structure are preserved in the text.
  expected_output: >
    A clean, combined text output from all PDFs, separated by file names for clarity.
  agent: pdf_extractor_agent

summarisation_task:
  description: >
    Create well-structured and concise study notes from the extracted text.
    The notes should be suitable for quick revision before exams — covering all key concepts, definitions,
    explanations, and important points.
    Use markdown formatting with headings, subheadings, and bullet points, but do not include triple backticks or code blocks.
    Highlight formulas, dates, keywords, and definitions clearly.
  expected_output: >
    A set of properly organised study notes in markdown format, tailored for effective exam preparation.
    Each document's notes should be clearly separated with its title.
  agent: summariser_agent
